name: Pipeline

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run command
      run: python hello.py
  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pythonart
        path: .